from stanfordkarel import *

def main():
    """Karel code goes here!"""
    # move() - move
    # turn_left() - rotate 90 degrees
    # put_beeper()
    move()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    turn_left()
    move()
    put_beeper()
    turn_left()
    move()
    move()
    move()
    move()
    move()
    put_beeper()
    turn_left()
    turn_left()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    move()
    move()
    move()
    put_beeper()
    turn_left()
    move()
    turn_left()
    move()
    put_beeper()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    turn_left()
    move()
    put_beeper()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    turn_left()
    move()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()

if __name__ == "__main__":
    run_karel_program()

""" 
function move_place_beeper_east:
    move()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    
function move_place_beeper_north:
    turn_left()
    move()
    put_beeper()
    
function move_place_beeper_west:
    turn_left()
    move()
    move()
    move()
    move()
    move()
    put_beeper()
    
function move_north:
    turn_left()
    turn_left()
    turn_left()
    move()
    
function move_place_beeper_east:
    turn_left()
    turn_left()
    turn_left()
    move()
    move()
    move()
    move()
    put_beeper()
    
function move_north:
    turn_left()
    move()
    
function move_place_beeper_west:
    turn_left()
    move()
    put_beeper()
    move()
    
function move_place_beeper_north:
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    
function move_place_beeper_west:
    turn_left()
    move()
    put_beeper()
    move()
    
fucntion move_place_beeper_north:
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    
function move_place_beeper_east:
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    put_beeper()
    move()
    
function move_place_beeper_south:
    turn_left()
    turn_left()
    turn_left()
    move()
    put_beeper()
    
function move_east_north:
    turn_left()
    move()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    
"""
